import { QualityInspectionService } from '../refinement/quality-inspection.service';
import { qualityIssue, type QualityIssue, type QualityStage } from './quality-issue';

/** Observed stylistic risks, never a probability that a text was generated by AI. */
export function styleFingerprint(input: {
  projectId: string; runId: string; content: string;
  stage?: QualityStage;
  previousChapters: Array<{ id: string; content: string }>;
  characterNames: string[];
}) {
  const base = new QualityInspectionService().detectAiFingerprints(input.content);
  const issues: QualityIssue[] = [];
  const risk = (ruleId: string, quote: string, message: string) => issues.push(qualityIssue({
    ...input, stage: input.stage ?? 'chapter', ruleId, severity: 'medium', source: 'ai_trace_heuristic_v3',
    quote, message: `${message}；这是启发式风险，须由证据化语义评审确认`,
  }));
  const sentences = input.content.match(/[^。！？\n]+[。！？]/g)?.map(s => s.trim()).filter(s => s.length >= 20) || [];
  const repeats = [...new Set(sentences)].filter(s => input.previousChapters.some(c => c.content.includes(s)));
  if (repeats.length >= 3) issues.push(qualityIssue({ ...input, stage: input.stage ?? 'chapter', ruleId: 'style.cross_chapter_repetition',
    // 跨章逐字重复是文风/模板复用风险，不是与大纲互斥的事实错误：保持 P1 可见并参与一次局部修复，
    // 但不作为阻断项。否则它会绕过「文风建议不阻断保存」的收敛设计，在最终统一质量 Gate 直接卡死整章。
    severity: 'high', source: 'style_fingerprint_v2', quote: repeats[0],
    message: `与已写章节逐字重复至少 ${repeats.length} 个长句，须核对是否为有意引用并局部修订` }));

  // Cross-chapter fragments catch recycled templates even when punctuation or
  // sentence boundaries changed. Only literal 18-character evidence is used.
  const normalizedPrevious = input.previousChapters.map(chapter => chapter.content.replace(/[\s，。！？；：“”「」]/g, ''));
  const compact = input.content.replace(/[\s，。！？；：“”「」]/g, '');
  const fragmentHits: string[] = [];
  for (let index = 0; index + 18 <= compact.length; index += 9) {
    const fragment = compact.slice(index, index + 18);
    if (normalizedPrevious.some(chapter => chapter.includes(fragment))) fragmentHits.push(fragment);
  }
  const uniqueFragments = [...new Set(fragmentHits)];
  if (uniqueFragments.length >= 2) issues.push(qualityIssue({ ...input, stage: input.stage ?? 'chapter',
    ruleId: 'style.cross_chapter_fragments', severity: 'high', source: 'style_fingerprint_v2',
    quote: uniqueFragments[0], content: compact,
    message: `与已有章节重复 ${uniqueFragments.length} 个连续长片段，需检查模板复用或误复制` }));

  const paragraphs = input.content.split(/\n+/).map(p => p.trim()).filter(p => p.length >= 20);
  const starts = new Map<string, string[]>();
  for (const p of paragraphs) {
    const key = p.slice(0, 8);
    starts.set(key, [...(starts.get(key) || []), p]);
  }
  for (const group of starts.values()) if (group.length >= 3) issues.push(qualityIssue({ ...input,
    stage: input.stage ?? 'chapter', ruleId: 'style.paragraph_opening', severity: 'high', source: 'style_fingerprint_v2',
    quote: group[0], message: `${group.length} 段使用相同开头，需核对叙事结构是否机械重复` }));

  const transitionGroups = new Map<string, string[]>();
  for (const paragraph of paragraphs) {
    const transition = paragraph.match(/^(然而|与此同时|就在这时|下一秒|紧接着|不知过了多久|片刻之后)/)?.[1];
    if (transition) transitionGroups.set(transition, [...(transitionGroups.get(transition) || []), paragraph]);
  }
  for (const [transition, group] of transitionGroups) if (group.length >= 3) issues.push(qualityIssue({ ...input,
    stage: input.stage ?? 'chapter', ruleId: 'style.cross_paragraph_transition', severity: 'high',
    source: 'style_fingerprint_v2', quote: group[0],
    message: `${group.length} 段用“${transition}”启动，跨段推进方式机械重复` }));

  // Attribute dialogue only when a known speaker is explicitly named on the same line.
  const voices = new Map<string, Set<string>>();
  for (const line of input.content.split(/\n+/)) {
    const speakers = input.characterNames.filter(name => line.startsWith(name));
    if (speakers.length !== 1) continue;
    for (const match of line.matchAll(/[“「]([^”」]{12,})[”」]/g)) {
      const quote = match[1];
      if (!voices.has(quote)) voices.set(quote, new Set());
      voices.get(quote)!.add(speakers[0]);
    }
  }
  for (const [quote, speakers] of voices) if (speakers.size >= 2) issues.push(qualityIssue({ ...input,
    stage: input.stage ?? 'chapter', ruleId: 'style.character_voice', severity: 'high', source: 'style_fingerprint_v2', quote,
    message: `${[...speakers].join('、')}使用逐字相同的长台词，需核对角色声音或有意复述` }));

  // Compare voice profiles only with enough explicitly attributed dialogue.
  const attributed = new Map<string, string[]>();
  for (const line of input.content.split(/\n+/)) {
    const speaker = input.characterNames.find(name => line.startsWith(name));
    if (!speaker) continue;
    const quotes = [...line.matchAll(/[“「]([^”」]{8,})[”」]/g)].map(match => match[1]);
    if (quotes.length) attributed.set(speaker, [...(attributed.get(speaker) || []), ...quotes]);
  }
  const heuristicPatterns: Array<[string, RegExp, string]> = [
    ['ai_trace.emotion_overexplanation_risk', /[^。！？\n]{0,30}(?:感到|情绪|内心|心中)[^。！？\n]{0,20}(?:因为|意味着|说明)[^。！？\n]{0,35}[。！？]?/, '情绪后紧跟解释性归因'],
    ['ai_trace.causal_author_explanation_risk', /[^。！？\n]{0,20}(?:之所以|显然|毫无疑问)[^。！？\n]{0,60}[。！？]?/, '叙述者可能直接替读者解释因果'],
    ['ai_trace.functional_complete_dialogue_risk', /[“「][^”」]{0,20}(?:首先|其次|最后|总之)[^”」]{20,120}[”」]/, '对白可能过度完整地传递功能信息'],
    ['ai_trace.transparent_character_cognition_risk', /[^。！？\n]{0,25}(?:他|她|他们)(?:清楚地知道|完全明白|立刻意识到)[^。！？\n]{0,60}[。！？]?/, '人物认知可能被叙述得过度透明'],
    ['ai_trace.abstract_summary_risk', /[^。！？\n]{0,20}(?:这就是|归根结底|人生|命运|意义在于)[^。！？\n]{10,70}[。！？]?/, '段落可能以抽象总结替代具体行动或感受'],
  ];
  for (const [ruleId, pattern, message] of heuristicPatterns) {
    const match = input.content.match(pattern)?.[0]?.trim();
    if (match) risk(ruleId, match, message);
  }
  const functions = paragraphs.map(paragraph => ({
    paragraph,
    signature: [
      /[“「]/.test(paragraph) ? 'dialogue' : 'narration',
      /(突然|忽然|下一秒|就在这时)/.test(paragraph) ? 'turn' : 'steady',
      /(因为|所以|意味着|说明)/.test(paragraph) ? 'explain' : 'show',
    ].join(':'),
  }));
  const functionGroups = new Map<string, string[]>();
  for (const item of functions) functionGroups.set(item.signature, [...(functionGroups.get(item.signature) || []), item.paragraph]);
  for (const [signature, group] of functionGroups) if (group.length >= 5 && group.length / paragraphs.length >= 0.7) {
    risk('ai_trace.paragraph_function_homology_risk', group[0], `${group.length} 段呈现相同的“${signature}”粗粒度功能结构`);
  }
  const profiles = [...attributed.entries()].filter(([, quotes]) => quotes.length >= 5 && quotes.join('').length >= 80)
    .map(([name, quotes]) => {
      const joined = quotes.join('');
      return { name, quotes, vector: [
        quotes.reduce((sum, quote) => sum + quote.length, 0) / quotes.length / 40,
        (joined.match(/[？！!?]/g) || []).length / quotes.length,
        (joined.match(/[啊吧呢嘛呀]/g) || []).length / quotes.length,
        (joined.match(/[我俺咱]/g) || []).length / Math.max(1, joined.length),
      ] };
    });
  for (let left = 0; left < profiles.length; left += 1) for (let right = left + 1; right < profiles.length; right += 1) {
    const distance = profiles[left].vector.reduce((sum, value, index) => sum + Math.abs(value - profiles[right].vector[index]), 0);
    if (distance <= 0.12) issues.push(qualityIssue({ ...input, stage: input.stage ?? 'chapter',
      ruleId: 'style.character_voice_profile', severity: 'medium', source: 'style_fingerprint_v2',
      quote: profiles[right].quotes[0],
      message: `${profiles[left].name}与${profiles[right].name}在足量台词中的句长、语气和口头词高度同构，需结合角色设定复核声音区分` }));
  }
  return { version: 3, status: input.content.trim().length >= 200 ? 'heuristic' : 'insufficient_evidence',
    base, issues, coverage: { paragraphs: paragraphs.length, previousChapters: input.previousChapters.length,
      namedCharacters: input.characterNames.length, attributedVoiceProfiles: profiles.length },
    repeatedSentences: repeats, repeatedFragments: uniqueFragments };
}
