import { QualityInspectionService } from '../refinement/quality-inspection.service';
import { qualityIssue, type QualityIssue, type QualityStage } from './quality-issue';

/** Observed stylistic risks, never a probability that a text was generated by AI. */
export function styleFingerprint(input: {
  projectId: string; runId: string; content: string;
  stage?: QualityStage;
  previousChapters: Array<{ id: string; content: string }>;
  characterNames: string[];
}) {
  const base = new QualityInspectionService().detectAiFingerprints(input.content);
  const issues: QualityIssue[] = [];
  const sentences = input.content.match(/[^。！？\n]+[。！？]/g)?.map(s => s.trim()).filter(s => s.length >= 20) || [];
  const repeats = [...new Set(sentences)].filter(s => input.previousChapters.some(c => c.content.includes(s)));
  if (repeats.length >= 3) issues.push(qualityIssue({ ...input, stage: input.stage ?? 'chapter', ruleId: 'style.cross_chapter_repetition',
    severity: 'blocking', source: 'style_fingerprint_v2', quote: repeats[0],
    message: `与已写章节逐字重复至少 ${repeats.length} 个长句，须核对是否为有意引用并局部修订` }));

  const paragraphs = input.content.split(/\n+/).map(p => p.trim()).filter(p => p.length >= 20);
  const starts = new Map<string, string[]>();
  for (const p of paragraphs) {
    const key = p.slice(0, 8);
    starts.set(key, [...(starts.get(key) || []), p]);
  }
  for (const group of starts.values()) if (group.length >= 3) issues.push(qualityIssue({ ...input,
    stage: input.stage ?? 'chapter', ruleId: 'style.paragraph_opening', severity: 'high', source: 'style_fingerprint_v2',
    quote: group[0], message: `${group.length} 段使用相同开头，需核对叙事结构是否机械重复` }));

  // Attribute dialogue only when a known speaker is explicitly named on the same line.
  const voices = new Map<string, Set<string>>();
  for (const line of input.content.split(/\n+/)) {
    const speakers = input.characterNames.filter(name => line.startsWith(name));
    if (speakers.length !== 1) continue;
    for (const match of line.matchAll(/[“「]([^”」]{12,})[”」]/g)) {
      const quote = match[1];
      if (!voices.has(quote)) voices.set(quote, new Set());
      voices.get(quote)!.add(speakers[0]);
    }
  }
  for (const [quote, speakers] of voices) if (speakers.size >= 2) issues.push(qualityIssue({ ...input,
    stage: input.stage ?? 'chapter', ruleId: 'style.character_voice', severity: 'high', source: 'style_fingerprint_v2', quote,
    message: `${[...speakers].join('、')}使用逐字相同的长台词，需核对角色声音或有意复述` }));
  return { version: 2, status: input.content.trim().length >= 200 ? 'heuristic' : 'insufficient_evidence',
    base, issues, coverage: { paragraphs: paragraphs.length, previousChapters: input.previousChapters.length,
      namedCharacters: input.characterNames.length }, repeatedSentences: repeats };
}
