import React, { useEffect, useState } from 'react';
import { api } from '../../lib/api';

const relationTypes = [['contains','包含'],['belongs_to','隶属'],['adjacent_to','相邻'],['route_to','通往'],['hidden_path_to','隐藏路径'],['controlled_by','受控于'],['conflicts_with','冲突区'],['mirrors','镜像对应'],['foreshadows','伏笔指向'],['blocked_by','被阻断']];
const relationFields = ['target_location_id','relation_description','distance_cost','travel_time','travel_method','risk_level','access_condition'];
const labels: Record<string, string> = { target_location_id:'目标地点', relation_description:'关系说明', distance_cost:'距离成本', travel_time:'移动时间', travel_method:'交通方式', risk_level:'风险等级', access_condition:'通行条件' };
const payload = (value: any) => value?.data?.data ?? value?.data ?? value ?? {};

// 对齐《世界观模板》的地点 / 氛围 / 势力段落（聚焦 10 项）
const profileSections: Array<[string, string, string[]]> = [
  ['基础定位','定义地点类型与地理位置。',['location_type','geography_position']],
  ['描述与氛围','可直接用于正文的基础描述、氛围与关键地标。',['basic_description','atmosphere','key_landmarks']],
  ['归属与资源','明确掌控势力、资源与稀缺。',['controlling_force','resources_scarcity']],
  ['秘密与关联','隐藏秘密/伏笔钩子，以及关联人物与章节。',['secrets_foreshadow','connected_characters','connected_chapters']],
];
const profileLabels: Record<string, string> = { ...labels, location_type:'地点类型',geography_position:'地理位置与方位',basic_description:'基础描述',atmosphere:'氛围与环境',key_landmarks:'关键地点/标志物',controlling_force:'掌控势力/角色',resources_scarcity:'资源与稀缺',secrets_foreshadow:'隐藏秘密/伏笔钩子',connected_characters:'关联人物',connected_chapters:'关联章节' };
const LocationKnowledgeEditor: React.FC<{ projectId:string; mapPointId:string }> = ({ projectId, mapPointId }) => { const [profile,setProfile]=useState<Record<string,string>>({}); const [relations,setRelations]=useState<any[]>([]); const [summary,setSummary]=useState(''); const load=async()=>{const [p,s]=await Promise.all([api.get(`/projects/${projectId}/map-points/${mapPointId}/profile`),api.get(`/projects/${projectId}/map-points/${mapPointId}/writing-summary`)]);setProfile(payload(p).profile||{});setRelations(payload(p).relations||[]);setSummary(payload(s).summary||'');};useEffect(()=>{void load();},[projectId,mapPointId]);const updateRelation=(index:number,patch:Record<string,unknown>)=>setRelations(rows=>rows.map((row,i)=>i===index?{...row,...patch}:row));const addRelation=()=>setRelations(rows=>[...rows,{target_location_id:'',relation_type:'route_to',is_hidden:false,is_one_way:false}]);const removeRelation=(index:number)=>setRelations(rows=>rows.filter((_,i)=>i!==index));const save=async()=>{await api.put(`/projects/${projectId}/map-points/${mapPointId}/profile`,profile);await api.put(`/projects/${projectId}/map-points/${mapPointId}/relations`,{relations});await load();};return <section style={{padding:16,borderTop:'1px solid #ddd'}}><h2>地点知识图谱</h2><pre style={{whiteSpace:'pre-wrap',maxHeight:180,overflow:'auto'}}>{summary||'保存后生成地点写作摘要。'}</pre>{profileSections.map(([title,description,fields])=><section key={title}><h3>{title}</h3><p>{description}</p>{fields.map(field=><label key={field} style={{display:'block'}}>{profileLabels[field]}<textarea value={profile[field]||''} onChange={event=>setProfile({...profile,[field]:event.target.value})}/></label>)}</section>)}<section><h3>地点关系</h3>{relations.length===0&&<p>暂无地点关系</p>}{relations.map((relation,index)=><article key={relation.id||index}><select value={relation.relation_type||'route_to'} onChange={event=>updateRelation(index,{relation_type:event.target.value})}>{relationTypes.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{relationFields.map(field=><label key={field}>{labels[field]}<input value={relation[field]||''} onChange={event=>updateRelation(index,{[field]:event.target.value})}/></label>)}<label><input type="checkbox" checked={Boolean(relation.is_hidden)} onChange={event=>updateRelation(index,{is_hidden:event.target.checked})}/>隐藏关系</label><label><input type="checkbox" checked={Boolean(relation.is_one_way)} onChange={event=>updateRelation(index,{is_one_way:event.target.checked})}/>单向关系</label><button type="button" onClick={()=>removeRelation(index)}>删除关系</button></article>)}<button type="button" onClick={addRelation}>新增地点关系</button></section><button type="button" onClick={save}>保存地点知识图谱</button></section>; };

export const LocationKnowledgePanelV2: React.FC<{ projectId: string; mapPointId: string }> = ({ projectId, mapPointId }) => (
  <LocationKnowledgeEditor projectId={projectId} mapPointId={mapPointId} />
);