import React, { useEffect, useState } from 'react';
import { api } from '../../lib/api';

const relationTypes = [['contains','包含'],['belongs_to','隶属'],['adjacent_to','相邻'],['route_to','通往'],['hidden_path_to','隐藏路径'],['controlled_by','受控于'],['conflicts_with','冲突区'],['mirrors','镜像对应'],['foreshadows','伏笔指向'],['blocked_by','被阻断']];
const relationFields = ['target_location_id','relation_description','distance_cost','travel_time','travel_method','risk_level','access_condition'];
const labels: Record<string, string> = { target_location_id:'目标地点', relation_description:'关系说明', distance_cost:'距离成本', travel_time:'移动时间', travel_method:'交通方式', risk_level:'风险等级', access_condition:'通行条件' };
const payload = (value: any) => value?.data?.data ?? value?.data ?? value ?? {};

const profileSections: Array<[string, string, string[]]> = [
  ['基础定位','定义地点身份、层级和地图位置。',['location_name','location_alias','location_type','parent_location_id','hierarchy_path']],
  ['感官与氛围','记录可直接用于正文的感官描写。',['basic_description','visual_features','sound_smell_texture','atmosphere','symbolic_meaning']],
  ['路线与空间逻辑','约束移动、入口与隐藏路径。',['geography_position','distance_logic','traffic_routes','entry_conditions','exit_conditions','hidden_paths']],
  ['归属与控制','明确地点控制权和安全边界。',['owner_force','controlling_character','public_identity','secret_identity','security_level','surveillance_level']],
  ['剧情功能','说明地点如何推动冲突和伏笔。',['location_function','plot_function','conflict_function','foreshadowing_function','resource_function','encounter_function']],
  ['状态与规则','记录当前状态、禁令和惩罚。',['current_status','status_reason','danger_level','forbidden_behaviors','rules_inside','punishment_inside']],
  ['资源价值','明确资源、物品与战略价值。',['available_resources','scarce_resources','special_items','trade_value','strategic_value']],
  ['历史秘密','承载历史、灾难与隐藏真相。',['historical_events','past_disaster','war_memory','lost_truth','secret_buried_here']],
  ['关联对象','连接角色、势力、伏笔和章节。',['connected_characters','connected_forces','connected_foreshadowing','connected_chapters','connected_world_rules']],
  ['场景写作卡','为抵达、重访和高潮提供素材。',['scene_hooks','sensory_anchor','first_arrival_impression','revisit_changes','climax_usage']],
  ['AI 写作约束','记录必须遵守与禁止写法。',['must_obey_rules','can_change_rules','forbidden_writing','easy_to_break_points','current_chapter_usage']],
];
const profileLabels: Record<string, string> = { ...labels, location_name:'地点名称',location_alias:'地点别名',location_type:'地点类型',parent_location_id:'上级地点',hierarchy_path:'层级路径',basic_description:'基础描述',visual_features:'视觉特征',sound_smell_texture:'声音气味触感',atmosphere:'地点氛围',symbolic_meaning:'象征意义',geography_position:'地理位置',distance_logic:'距离逻辑',traffic_routes:'交通路线',entry_conditions:'进入条件',exit_conditions:'离开条件',hidden_paths:'隐藏路径',owner_force:'控制势力',controlling_character:'控制角色',public_identity:'公开身份',secret_identity:'秘密身份',security_level:'安保等级',surveillance_level:'监视等级',location_function:'地点功能',plot_function:'剧情功能',conflict_function:'冲突功能',foreshadowing_function:'伏笔功能',resource_function:'资源功能',encounter_function:'遭遇功能',current_status:'当前状态',status_reason:'状态原因',danger_level:'危险等级',forbidden_behaviors:'禁止行为',rules_inside:'内部规则',punishment_inside:'违规惩罚',available_resources:'可用资源',scarce_resources:'稀缺资源',special_items:'特殊物品',trade_value:'交易价值',strategic_value:'战略价值',historical_events:'历史事件',past_disaster:'过去灾难',war_memory:'战争记忆',lost_truth:'失落真相',secret_buried_here:'埋藏秘密',connected_characters:'关联角色',connected_forces:'关联势力',connected_foreshadowing:'关联伏笔',connected_chapters:'关联章节',connected_world_rules:'关联世界规则',scene_hooks:'场景钩子',sensory_anchor:'感官锚点',first_arrival_impression:'首次到达印象',revisit_changes:'重访变化',climax_usage:'高潮用途',must_obey_rules:'必须遵守',can_change_rules:'允许变化',forbidden_writing:'禁止写法',easy_to_break_points:'容易写崩点',current_chapter_usage:'本章可用' };
const LocationKnowledgeEditor: React.FC<{ projectId:string; mapPointId:string }> = ({ projectId, mapPointId }) => { const [profile,setProfile]=useState<Record<string,string>>({}); const [relations,setRelations]=useState<any[]>([]); const [summary,setSummary]=useState(''); const load=async()=>{const [p,s]=await Promise.all([api.get(`/projects/${projectId}/map-points/${mapPointId}/profile`),api.get(`/projects/${projectId}/map-points/${mapPointId}/writing-summary`)]);setProfile(payload(p).profile||{});setRelations(payload(p).relations||[]);setSummary(payload(s).summary||'');};useEffect(()=>{void load();},[projectId,mapPointId]);const updateRelation=(index:number,patch:Record<string,unknown>)=>setRelations(rows=>rows.map((row,i)=>i===index?{...row,...patch}:row));const addRelation=()=>setRelations(rows=>[...rows,{target_location_id:'',relation_type:'route_to',is_hidden:false,is_one_way:false}]);const removeRelation=(index:number)=>setRelations(rows=>rows.filter((_,i)=>i!==index));const save=async()=>{await api.put(`/projects/${projectId}/map-points/${mapPointId}/profile`,profile);await api.put(`/projects/${projectId}/map-points/${mapPointId}/relations`,{relations});await load();};return <section style={{padding:16,borderTop:'1px solid #ddd'}}><h2>地点知识图谱</h2><pre style={{whiteSpace:'pre-wrap',maxHeight:180,overflow:'auto'}}>{summary||'保存后生成地点写作摘要。'}</pre>{profileSections.map(([title,description,fields])=><section key={title}><h3>{title}</h3><p>{description}</p>{fields.map(field=><label key={field} style={{display:'block'}}>{profileLabels[field]}<textarea value={profile[field]||''} onChange={event=>setProfile({...profile,[field]:event.target.value})}/></label>)}</section>)}<section><h3>地点关系</h3>{relations.length===0&&<p>暂无地点关系</p>}{relations.map((relation,index)=><article key={relation.id||index}><select value={relation.relation_type||'route_to'} onChange={event=>updateRelation(index,{relation_type:event.target.value})}>{relationTypes.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{relationFields.map(field=><label key={field}>{labels[field]}<input value={relation[field]||''} onChange={event=>updateRelation(index,{[field]:event.target.value})}/></label>)}<label><input type="checkbox" checked={Boolean(relation.is_hidden)} onChange={event=>updateRelation(index,{is_hidden:event.target.checked})}/>隐藏关系</label><label><input type="checkbox" checked={Boolean(relation.is_one_way)} onChange={event=>updateRelation(index,{is_one_way:event.target.checked})}/>单向关系</label><button type="button" onClick={()=>removeRelation(index)}>删除关系</button></article>)}<button type="button" onClick={addRelation}>新增地点关系</button></section><button type="button" onClick={save}>保存地点知识图谱</button></section>; };

export const LocationKnowledgePanelV2: React.FC<{ projectId: string; mapPointId: string }> = ({ projectId, mapPointId }) => {
  return <LocationKnowledgeEditor projectId={projectId} mapPointId={mapPointId} />;
  const [profile, setProfile] = useState<Record<string, string>>({});
  const [relations, setRelations] = useState<any[]>([]);
  const [summary, setSummary] = useState('');
  const [notice, setNotice] = useState('');
  const load = async () => { const [profileRes, summaryRes] = await Promise.all([api.get(`/projects/${projectId}/map-points/${mapPointId}/profile`), api.get(`/projects/${projectId}/map-points/${mapPointId}/writing-summary`)]); setProfile(payload(profileRes).profile || {}); setRelations(payload(profileRes).relations || []); setSummary(payload(summaryRes).summary || ''); };
  useEffect(() => { void load(); }, [projectId, mapPointId]);
  const updateRelation = (index: number, patch: Record<string, unknown>) => setRelations(rows => rows.map((row, i) => i === index ? { ...row, ...patch } : row));
  const addRelation = () => setRelations(rows => [...rows, { target_location_id: '', relation_type: 'route_to', is_hidden: false, is_one_way: false }]);
  const removeRelation = (index: number) => setRelations(rows => rows.filter((_, i) => i !== index));
  const save = async () => { setNotice('正在保存...'); const saved = await api.put(`/projects/${projectId}/map-points/${mapPointId}/profile`, profile); await api.put(`/projects/${projectId}/map-points/${mapPointId}/relations`, { relations }); setProfile(payload(saved).profile || profile); await load(); setNotice('已保存。'); };
  return <section style={{ padding: 16, borderTop: '1px solid #ddd' }}><h2>地点知识图谱</h2><pre style={{ whiteSpace: 'pre-wrap', maxHeight: 180, overflow: 'auto' }}>{summary || '保存后生成地点写作摘要。'}</pre><h3>地点关系</h3><p>维护层级、路线、控制和隐藏入口关系。</p>{relations.length === 0 && <p>暂无地点关系</p>}{relations.map((relation, index) => <article key={relation.id || index} style={{ border: '1px solid #ddd', padding: 10, marginBottom: 10 }}><strong>关系 {index + 1}</strong><label style={{ display: 'block' }}>关系类型<select value={relation.relation_type || 'route_to'} onChange={event => updateRelation(index, { relation_type: event.target.value })}>{relationTypes.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{relationFields.map(field => <label key={field} style={{ display: 'block' }}>{labels[field]}<input value={relation[field] || ''} onChange={event => updateRelation(index, { [field]: event.target.value })} /></label>)}<label><input type="checkbox" checked={Boolean(relation.is_hidden)} onChange={event => updateRelation(index, { is_hidden: event.target.checked })} /> 隐藏关系</label><label><input type="checkbox" checked={Boolean(relation.is_one_way)} onChange={event => updateRelation(index, { is_one_way: event.target.checked })} /> 单向关系</label><button type="button" onClick={() => removeRelation(index)}>删除关系</button></article>)}<button type="button" onClick={addRelation}>新增地点关系</button><button type="button" onClick={save}>保存地点关系</button>{notice && <p>{notice}</p>}</section>;
};
